# Generated by Django 5.0.1 on 2024-02-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ucenik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=20)),
                ('Prezime', models.CharField(max_length=20)),
                ('DatumRodjenja', models.DateField()),
            ],
        ),
    ]
