# Generated by Django 5.0.1 on 2024-03-08 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skolaweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nastavnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=20)),
                ('Prezime', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SkolskaGodina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oznaka', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Razred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oznaka', models.CharField(max_length=20)),
                ('Razrednik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skolaweb.nastavnik')),
                ('Ucenici', models.ManyToManyField(to='skolaweb.ucenik')),
                ('SkolskaGodina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skolaweb.skolskagodina')),
            ],
        ),
    ]
